version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - learningafrica_web
  learningafrica_web:
    build: ./backend_la
    command: gunicorn base_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend_la:/app
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
   image: postgres:15
   restart: on-failure
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=myPostGressAcc1**
     - POSTGRES_DB=learningafrica_backend_db
   volumes:
     -  db:/var/lib/postgresql/data

volumes:
  db: