version: '3.8'

services:
  learningafrica_web:
    build: ./backend_la
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_la:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
   image: postgres:15
   restart: on-failure
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=myPostGressAcc1**
     - POSTGRES_DB=learningafrica_backend_db
   volumes:
     -  db:/var/lib/postgresql/data

volumes:
  db: