# Generated by Django 4.2.7 on 2024-06-06 13:10

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, editable=False, length=12, max_length=12, null=True, prefix='')),
                ('user_type', models.CharField(choices=[('adm', 'Admin'), ('ins', 'Instructor'), ('stu', 'Student')], max_length=3)),
                ('is_used', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=500)),
                ('expiration_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
    ]
